### ISSUE TITLE
[FEATURE] - add topic 'github-action' so it will be available as an Github Action 

### ISSUE THREAD

**Issue by Justin-JHG** [marcelblijleven/jira-helper#10]
can we please expose this as a Github Action on the market place? 

so it can get the following : 

![image](https://user-images.githubusercontent.com/41654878/202938438-25ae6335-2d22-4c6f-81c7-8da657512635.png)

**Comment by Justin-JHG** [comment]
FYI - @marcelblijleven

**Comment by marcelblijleven** [comment]
Hi I looked into it and it seems adding the tag alone isn’t enough to make it available in the marketplace: https://docs.github.com/en/actions/creating-actions/publishing-actions-in-github-marketplace

**Comment by Justin-JHG** [comment]
Oh I see, thanks, so need a action.yml file
