### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by Justin-JHG** [marcelblijleven/jira-helper#6]
Can this be used to create fix version when pull request merged? And find jira issue number from pull request description?

If so can you please provide an example of GitHub actions?

Thanks 
Justin

**Comment by marcelblijleven** [comment]
Maybe, I haven't looked into it but if you can get the pull request info from the trigger event in Github Actions it should be possible. https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request
